icecream/flavours/urls.py
from django.conf.urls import patterns, url

from .views import FlavourCreateView, FlavourUpdateView, FlavourDetailView

urlpatterns = patterns('',
    
    # ex: /guides/make-a-seashell-candle
    url(r'^create/$', FlavourCreateView.as_view(template_name="create.html"), name="create"),
    url(r'^update/(?P<slug>[-\w]+)$', FlavourUpdateView.as_view(template_name="update.html"), name="update"),
    url(r'^(?P<slug>[-\w]+)/$', FlavourDetailView.as_view(template_name="detail.html"), name="detail"),
    #url(r'^(?P<slug>[-\w]+)/$', FlavourDetailView.as_view(template_name='detail.html', name='detail'),
    #url(r'^create/$', 'guides.views.create', name='create'),
    #url(r'^create/(?P<guide_id>\d+)/material/$', 'guides.views.create_material', name='create_material'),
    #url(r'^create_steps/(?P<guide_id>\d+)/$', 'guides.views.create_steps', name='create_steps'),    
)

icecream/icecream/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

from flavours.views import FlavourListView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', FlavourListView.as_view(template_name="index.html"), name="index"),

    # Examples:
    # url(r'^$', 'icecream.views.home', name='home'),
    # url(r'^icecream/', include('icecream.foo.urls')),
    url(r'^flavours/', include('flavours.urls', namespace="flavours")),

    # User accounts
    (r'^accounts/', include('registration.backends.simple.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

# Uncomment the next line to serve media files in dev.
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
                            url(r'^__debug__/', include(debug_toolbar.urls)),
                            )

icecream/flavours/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.template.defaultfilters import slugify

# Create your models here.
class TimeStampedModel(models.Model):
    """
    An abstract base class model that provides self-
    updating ``created`` and ``modified`` fields.
    """
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Flavour(TimeStampedModel):
    name = models.CharField(max_length=200)
    color = models.CharField(max_length=200)
    slug = models.SlugField()
    scoops_remaining = models.IntegerField(null=True, blank=True)

    def get_absolute_url(self):
          return reverse("flavours:detail", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        if not self.id:
            # Newly created object, so set slug
            self.slug = slugify(self.name)
        models.Model.save(self, *args, **kwargs)

    def __unicode__(self):
        return self.name

icecream/flavours/forms.py
from django import forms
from django.forms import ModelForm

from .models import Flavour


class FlavourCreateForm(ModelForm):
    class Meta:
        model = Flavour
        fields = ("name", "color",)

    def __init__(self, *args, **kwargs):
        super(FlavourCreateForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['name'].widget.attrs['placeholder'] = 'Raspberry Love'
        self.fields['color'].widget.attrs['class'] = 'form-control'
        self.fields['color'].widget.attrs['placeholder'] = '#e94a39'
    
class FlavourUpdateForm(FlavourCreateForm):
    class Meta(FlavourCreateForm.Meta):
        fields = ("name", "color", "scoops_remaining",)    

class ScoopsUpdateForm(ModelForm):
    class Meta:
        model = Flavour
        exclude = ("slug", "name", "color", "scoops_remaining",)    

icecream/flavours/views.py
from django.contrib import messages
from django.forms.formsets import formset_factory, BaseFormSet
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, CreateView, UpdateView, DetailView


from braces.views import LoginRequiredMixin

from .models import Flavour
from .forms import FlavourCreateForm, FlavourUpdateForm, ScoopsUpdateForm

# Create your views here.
class FlavourActionMixin(object):

    @property
    def action(self):
        msg = "{0} is missing action.".format(self.__class__)
        raise NoteImplementedError(msg)

    def form_valid(self, form):
        flavour = form.save(commit=False)
        flavour.scoops_remaining = 40
        flavour.save()
        msg = "Flavour {0}!".format(self.action)
        messages.info(self.request, msg)
        return super(FlavourActionMixin, self).form_valid(form)

class FlavourListView(ListView):
    model = Flavour
    form_class = ScoopsUpdateForm
    
    def post(self, request):
        flavour_id = int(request.POST.get('flavour_id'))
        flavour = get_object_or_404(Flavour, pk=flavour_id)
        if 'one' in request.POST:
            flavour.scoops_remaining -= 1
            flavour.save()
        elif 'two' in request.POST:
            flavour.scoops_remaining -= 2
            flavour.save()
        return HttpResponseRedirect('/') 


class FlavourCreateView(LoginRequiredMixin, FlavourActionMixin, CreateView):
    model = Flavour
    form_class = FlavourCreateForm
    action = "created"

class FlavourUpdateView(LoginRequiredMixin, FlavourActionMixin, UpdateView):
    model = Flavour
    form_class = FlavourUpdateForm
    action = "updated"

class FlavourDetailView(DetailView):
    model = Flavour

icecream/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}icecream{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Nixie+One' rel='stylesheet' type='text/css'>
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- This file store project specific CSS -->
    <link href="{% static 'css/icecream.css' %}" rel="stylesheet">

    <!-- Use this to quickly test CSS changes in a template,
        then move to icecream.css -->
    {% block extra_css %}{% endblock extra_css %}
  </head>

  <body>

    <nav class="navbar navbar-default navbar-fixed-top navigation-bar" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand nixie" href="/">IceMaker Labs</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><a class="btn btn-warning btn-navbar" id="add-flavour-btn" href="{% url 'flavours:create' %}">Add Flavour</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'django.contrib.auth.views.logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'django.contrib.auth.views.login' %}">Login</a></li>
            {% endif %}
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <div class="container">
      {% if messages %}
    ￼￼<ul class="messages">
        {% for message in messages %}
        <li id="message_{{ forloop.counter }}"
          {% if message.tags %} class="{{ message.tags }}"
                  {% endif %}>
                  {{ message }}
        </li>
          {% endfor %}
      </ul>
      {% endif %}
    </div>

    <div class="container">
      {% block content %}
        
      {% endblock content %}

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- place project specific Javascript in this file -->
    <script src="{% static 'js/icecream.js' %}"></script>

    {% block extra_js %}{% endblock extra_js %}
  </body>
</html>

icecream/templates/create.html
{% extends 'base.html' %}

{% block title %} {% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <h3>Icemaker: <span class="uppercase">{{ user.username }}</h3>
    </div>
</div>
<div class="row">
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>
</div>
{% endblock %}

icecream/templates/detail.html
{% extends 'base.html' %}

{% block title %} {% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <h3>Icemaker: <span class="uppercase">{{ user.username }}</h3>
    </div>
</div>
<div class="row">
    {% for flavour in object_list %}
    <div class="col-md-4 icecream-list">
        <div class="icecream-tub" style="background-color: {{ flavour.color }}"></div>
        <p class="nixie">{{ flavour.name }}</p>
        <p class="nixie">{{ flavour.created }}</p>
    </div>
    {% endfor %}
</div>
{% endblock %}

icecream/templates/index.html
{% extends 'base.html' %}

{% block title %} {% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <h3>Icemaker: <span class="uppercase">{{ user.username }}</h3>
    </div>
</div>
<div class="row">
    {% for flavour in object_list %}
    <div class="col-md-4 icecream-list">
        <h3 class="nixie">{{ flavour.name }}</h3>
        <a href="{% url 'flavours:update' slug=flavour.slug %}" class="btn btn-success edit-btn"><span class="glyphicon glyphicon-pencil"></span></a>
        <div class="icecream-tub" style="background-color: {{ flavour.color }}"></div>
        
        
        <form action="" method="post">
            {% csrf_token %}
            {{ scoops_update_form.as_p }}
            <span><strong>{{ flavour.scoops_remaining }}</strong></span><span class="nixie"> scoops remaining</span>
            <br/>
            <input type="hidden" name="flavour_id" value="{{ flavour.id }}"/>
            <input type="submit" class="btn btn-warning" name="one" value="Single Scoop"/>
            <input type="submit" class="btn btn-warning" name="two" value="Double Scoop"/>
        </form>
    </div>
    {% endfor %}
</div>
{% endblock %}

icecream/templates/update.html
{% extends 'base.html' %}

{% block title %} {% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <h3>Icemaker: <span class="uppercase">{{ user.username }}</h3>
    </div>
</div>
<div class="row">
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-success" value="Update" />
    </form>
</div>
{% endblock %}